version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ~/Volumes/postgresql-testik:/var/lib/postgresql/data


