"""empty message

Revision ID: 9435dbd9f75b
Revises: 
Create Date: 2023-09-22 02:22:45.725429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9435dbd9f75b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_users_groups',
    sa.Column('user_personal_number', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_personal_number', 'group_id')
    )
    op.create_table('dbo_solution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_personal_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_personal_number', 'group_id'], ['dbo_users_groups.user_personal_number', 'dbo_users_groups.group_id'], name='dbo_users_groups_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_solution')
    op.drop_table('dbo_users_groups')
    # ### end Alembic commands ###
